TOKEN_API = "5d3e03177c6d424d17f58f27362a845d"
TOKEN = "6002067245:AAFNpO7MpRh714amSvdKaSkuBdB55WCIWrI"
exchanges = {
    'U.S.dollar': 'USD',
    'Euro': 'EUR',
    'Russian_ruble': 'RUB',
    'Australian dollar': 'AUD',
    'Azerbaijani_manat':  'AZN',
    'Armenian_dram': 'AMD',
    'Belarusian_ruble': 'BYN',
    'Bulgarian_Lev': 'BGN',
    'Brazilian_Real': 'BRL',
    'Hungarian_forint': 'HUF',
    'Republic_of_Korea_Won': 'KRW',
    'Vietnamese_dong': 'VND',
    'Hong_Kong_dollar': 'HKD',
    'Georgian_lari': 'GEL',
    'Danish_krone': 'DKK',
    'United_Arab_Emirates_dirham': 'AED',
    'Egyptian_pounds': 'EGP',
    'Indian_rupees': 'INR',
    'Indonesian_Rupiah': 'IDR',
    'Kazakhstani_tenge': 'KZT',
    'Canadian_dollar': 'CAD',
    'Qatari_rial': 'QAR',
    'Kyrgyzstani_som': 'KGS',
    'Chinese_yuan': 'CNY',
    'Moldovan_lei': 'MDL',
    'New_Zealand_dollar': 'NZD',
    'Norwegian_kroner': 'NOK',
    'Polish_zloty': 'PLN',
    'Romanian_leu': 'RON',
    'Serbian_dinars': 'RSD',
    'Singapore_dollar': 'SGD',
    'Tajik_somoni': 'TJS',
    'Thai_baht': 'THB',
    'Turkish_Lira': 'TRY',
    'Uzbek_sum': 'UZS',
    'Ukrainian_hryvnia': 'UAH',
    'British_pound_sterling': 'GBP',
    'Czech_crowns': 'CZK',
    'Swedish_krona': 'SEK',
    'Swiss_frank': 'CHF',
    'South_African_rand': 'ZAR',
    'Japanese_yen': 'JPY'
}
