# Generated by Django 4.2.4 on 2023-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_surname', models.CharField(max_length=255)),
                ('article_topic', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_of_articles', models.CharField(choices=[('sprt', 'Sports'), ('pltc', 'Politics'), ('educ', 'Education'), ('mrkt', 'Markets'), ('ecms', 'Economics'), ('tech', 'Technology'), ('wlth', 'Wealth'), ('news', 'Breaking news')], default='news', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=255)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('comment_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_surname', models.CharField(max_length=255)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('article_topic', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=255)),
                ('text_of_articles', models.CharField(max_length=255)),
                ('categories_of_articles', models.CharField(choices=[('sprt', 'Sports'), ('pltc', 'Politics'), ('educ', 'Education'), ('mrkt', 'Markets'), ('ecms', 'Economics'), ('tech', 'Technology'), ('wlth', 'Wealth'), ('news', 'Breaking news')], max_length=4)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
